name: cart_storage_repository
description: A Dart Repository which manages the Lichi products.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  lichi_repository:
    path: ../lichi_repository

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.1
  json_serializable: ^6.7.1
