name: lichi_api
description: A Dart API Client for the Lichi API.
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.1
  json_serializable: ^6.7.1
